name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local action
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run lint
        run: npm run lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local action
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: npm run test

  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local action
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run build
        run: npm run build
